name: 🚀 Deploy Adapter Firmware

on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: 🚀 Build & Upload Adapter Firmware
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: 📥 Install Conan >=2.16.1
        run: pipx install conan>=2.16.1

      - name: 📡 Install libhal conan configuration
        run: conan config install https://github.com/libhal/conan-config2.git

      - name: 📡 Run hal setup
        run: conan hal setup

      - name: 📦 Build adapter firmware for target "stm32f103c8"
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: conan build adapter-firmware -pr:a hal/tc/llvm -pr:h hal/mcu/stm32f103c8

      - name: 📦 Build adapter firmware for target "stm32f103c8"
        if: startsWith(github.ref, 'refs/tags/')
        run: conan build adapter-firmware -pr:a hal/tc/llvm -pr:h hal/mcu/stm32f103c8 --version=${{ github.event.release.tag_name }}

      - name: 🚀 Push Binaries to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            adapter-firmware/build/stm32f103c8/MinSizeRel/app.elf
            adapter-firmware/build/stm32f103c8/MinSizeRel/app.elf.bin
